### ISSUE TITLE
求问 

### ISSUE THREAD

**Issue by SquirminatorHotHead** [TurtleZhong/camera_lidar_calibration_v2#4]
首先感谢您的工作！在这里我有一些小的问题想求教，代码里提供的bagfile好像比实际的要短不少，用代码里提供的 data.txt 文件里面的数据点，是可以calibrate的，但是我测试了用您给的sample begfile去采集数据点，测试类很多次，都无法得到好的结果，请问是我测量点的方法不对，还是这一段 bagfile确实无法提供有效的信息来做calibration？ 

4.091 -1.448 102.396 295.183
3.934 -1.856 150.463 295.506
3.595 -2.448 219.262 295.506
3.623 -2.706 237.624 294.143
3.972 -2.177 178.607 293.038
4.402 -1.177 62.6532 292.229
4.474 -0.933 32.6626 293.128
4.580 -1.186 60.1791 291.182
4.492 -1.481 95.1689 290.294
4.535 -1.344 77.6233 291.148

这些数据点在给的ROS bagfile 里好像都不存在

**Comment by TurtleZhong** [comment]
您好，项目过去比较久远了，我的bag应该只是小范围移动用来做可视化的我记得，应该是不满足标定要求的，标定的时候还是在有初值的时候尽量多移动视角去采值，这样比较有保证。

**Comment by TurtleZhong** [comment]
@anakin0620 您好，项目过去比较久远了，我的bag应该只是小范围移动用来做可视化的我记得，应该是不满足标定要求的，标定的时候还是在有初值的时候尽量多移动视角去采值，这样比较有保证。

**Comment by SquirminatorHotHead** [comment]
@TurtleZhong 感谢回复！做可视化现实结果确实不错！ 请问我是否可以帮您补充完善一下一些步骤的细节，这样后来的人可以更好得去使用这一套工具？

**Comment by TurtleZhong** [comment]
@anakin0620 完全没问题的啊，那您这边可以直接考虑fork一份然后提交merge进来？不知到是否可以呢，这样也许能帮到后面的人。

**Comment by SquirminatorHotHead** [comment]
@TurtleZhong 好的
